language: php

matrix:
  fast_finish: true
  include:
    - php: '7.1'
      install:
        - composer update --no-interaction
    - php: '7.2'
      install:
        - composer update --no-interaction
    - php: '7.3'
    - php: '7.4'
      after_script:
        - bash <(curl -s https://codecov.io/bash)
    - php: 'nightly'
      install:
        - composer install --no-interaction --ignore-platform-reqs
    - php: '7.3'
      name: 'Prefer lowest'
      install:
        - composer install --no-interaction
        - composer update --prefer-lowest
  allow_failures:
    - php: 'nightly'

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.cache/composer/files

install:
 - composer install --no-interaction

before_script:
 - echo 'date.timezone = "Europe/Oslo"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
 - vendor/bin/phpunit --version

script:
 - vendor/bin/phpunit
